# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# pod 'React.Framework', '~> 0.27.2'
pod 'React', '~> 0.13.0-rc'

pod 'CocoaLumberjack', '~> 3.5.3'
pod 'Masonry', '~> 1.1.0'
pod 'GCDWebServer', '~> 3.5.3'
pod 'MBProgressHUD', '~> 1.1.0'

target 'SRRNKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SRRNKit

end
